services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    #volumes:
     # - postgres-data:/var/lib/postgresql/data
     # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional seed data

  syncsenpai:
    image: syncsenpaiserver
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
       ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

volumes:
  postgres-data:
