services:
  aniarr:
    image: aniarrserver
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    environment:
      - MONGOSETTINGS__USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGOSETTINGS__PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGOSETTINGS__HOST=mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
    driver: bridge
