services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  syncsenpai:
    image: syncsenpaiserver
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - CONNECTION_STRING=host=${POSTGRES_HOST};port=${POSTGRES_PORT};database=${POSTGRES_DB};username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
